Update for CoreWeave SLURM
Fairly statically configured for 70 CPU, CPU nodes now

diff --git a/spark b/spark
--- a/spark
+++ b/spark
@@ -193,7 +193,7 @@ function start {
         | sed "s:<SOC_COPY_LOGS>:${soc_copy_logs}:g" \
         > "${cluster}/jobscript.sh"
     job_id=$(sbatch "${cluster}/jobscript.sh")
-    echo "${job_id}" > "${cluster}/slurm_job_id"
+    echo "${job_id}" | awk '{print $4;}' > "${cluster}/slurm_job_id"
     prop "job_id" "${job_id}" "${soc_prop}"
     info "Submitted job for cluster ${cluster_id}"
 }
@@ -273,6 +273,16 @@ function list {
             continue
         elif [[ -f "${cluster}/slurm_job_id" ]]; then
             job_id=$(cat "${cluster}/slurm_job_id")
+            if scontrol show jobs $job_id > /tmp/out 2> /dev/null; then
+                if grep CANCELLED /tmp/out > /dev/null; then
+                    continue
+                fi
+                master=$(awk '/master:/ {print $2}' "${cluster}/prop")
+                printf "%10s %12i %20s %26s\n" "${cluster_id}" "${job_id}" "${job_state}" "${master}"
+                show "${cluster_id}"
+            fi
+            continue
+            # Below is dead code until we have sacct /PS
             if [[ ${job_id} =~ [[:digit:]]+ ]]; then
                 job_state=$(sacct -j ${job_id} -PXn -o state)
                 if [[ "${job_state}" == "" ]]; then
@@ -324,6 +334,8 @@ function stop {
                 exit 1
             elif [[ -f "${cluster}/slurm_job_id" ]]; then
                 job_id=$(cat "${cluster}/slurm_job_id")
+                scancel ${job_id}
+                continue
                 if [[ ${job_id} =~ [[:digit:]]+ ]]; then
                     job_state=$(sacct -j ${job_id} -PXn -o state)
                     if [[ "${job_state}" == "" ]]; then
@@ -441,14 +453,11 @@ exit
 
 #__SBATCH__
 #! /bin/bash
-#SBATCH --constraint=cpu56,g256
 #SBATCH --nodes=<SOC_NNODES>
 #SBATCH --ntasks-per-node=1
-#SBATCH --cpus-per-task=56
-#SBATCH --mem-per-cpu=4400
+#SBATCH --cpus-per-task=70
 #SBATCH --time=<SOC_TIME>
-#SBATCH --partition=multinode
-#SBATCH --gres=lscratch:380
+#SBATCH --partition=cpu-xeon-v3
 #SBATCH --out=<SOC_SPARKLOGDIR>/slurm.log
 #SBATCH --signal=B:USR1@180
 
@@ -494,14 +503,16 @@ EOF
 }
 
 prop "start" "$(date +'%F %T')"
-module load spark/<SOC_SPARKVER> || fail "Could not load spark module"
+#module load spark/<SOC_SPARKVER> || fail "Could not load spark module"
 
 ###
 ### configuration files and job setup
 ###
 
 # Set up node local scratch directories on all the nodes
-export SCRATCH="/lscratch/${SLURM_JOB_ID}"
+export TMPDIR="/mnt/nvme/tmp/${SLURM_JOB_ID}"
+export SCRATCH="/tmp/${SLURM_JOB_ID}"
+srun -l mkdir "${SCRATCH}"
 export SPARK_CONF_DIR="${SCRATCH}/conf"
 srun -l mkdir "${SPARK_CONF_DIR}" \
     && srun -l mkdir "${SCRATCH}/logs" \
@@ -517,15 +528,13 @@ echo ${nodelist} | tr -s ' ' '\n' > "${SPARK_CONF_DIR}/slaves"
 
 # URIs - find free ports on biowulf first
 export SPARK_MASTER_WEBUI_PORT
-if ! SPARK_MASTER_WEBUI_PORT=$(ssh -oStrictHostKeyChecking=no -q biowulf-e0 '/usr/local/bin/portauthority'); then
-    SPARK_MASTER_WEBUI_PORT=$(( (RANDOM % 5000) + 31986 ))
-fi
+SPARK_MASTER_WEBUI_PORT=$(( (RANDOM % 5000) + 31986 ))
+
 
 export SPARK_MASTER_HOST="$( hostname -f )"
 export SPARK_MASTER_PORT
-if ! SPARK_MASTER_PORT=$(ssh -oStrictHostKeyChecking=no -q biowulf-e0 '/usr/local/bin/portauthority'); then
-    SPARK_MASTER_PORT=$(( (RANDOM % 5000) + 36986 ))
-fi
+SPARK_MASTER_PORT=$(( (RANDOM % 5000) + 36986 ))
+
 master="spark://${SPARK_MASTER_HOST}:${SPARK_MASTER_PORT}"
 master_webui="http://${SPARK_MASTER_HOST}:${SPARK_MASTER_WEBUI_PORT}"
 
@@ -535,13 +544,13 @@ prop "tunnel" "ssh -L ${SPARK_MASTER_WEBUI_PORT}:${SPARK_MASTER_HOST}:${SPARK_MA
 
 # create config file in tmp dir
 # NOTE: SPARK_WORKER_INSTANCES IS DEPRECATED
-cat > "/tmp/spark-env.sh" <<EOF 
-SPARK_WORKER_CORES=52
-SPARK_WORKER_MEMORY=235g
+cat > "${TMPDIR}/spark-env.sh" <<EOF 
+SPARK_WORKER_CORES=70
+SPARK_WORKER_MEMORY=180g
 SPARK_WORKER_DIR=${SCRATCH}/work
 SPARK_LOCAL_DIRS=${SCRATCH}/local
 SPARK_DAEMON_MEMORY=2g
-SPARK_CONF_DIR=${SLURM_CONF_DIR}
+SPARK_CONF_DIR=${SPARK_CONF_DIR}
 SPARK_LOG_DIR=${SCRATCH}/logs
 SPARK_PID_DIR=${SCRATCH}/pid
 SPARK_MASTER_WEBUI_PORT=${SPARK_MASTER_WEBUI_PORT}
@@ -550,16 +559,16 @@ SPARK_MASTER_PORT=${SPARK_MASTER_PORT}
 EOF
 
 # broadcast config file to each node
-sbcast /tmp/spark-env.sh ${SPARK_CONF_DIR}/spark-env.sh \
+srun cp ${TMPDIR}/spark-env.sh ${SPARK_CONF_DIR}/spark-env.sh \
     || fail "Could not broadcast config file to nodes"
 
 # modify the local copy of the config file to use fewer resources
-sed -i 's/SPARK_WORKER_CORES=52/SPARK_WORKER_CORES=44/; 
-        s/SPARK_WORKER_MEMORY=235g/SPARK_WORKER_MEMORY=230g/' \
-    "${SPARK_CONF_DIR}/spark-env.sh"
+#sed -i 's/SPARK_WORKER_CORES=52/SPARK_WORKER_CORES=44/; 
+#        s/SPARK_WORKER_MEMORY=235g/SPARK_WORKER_MEMORY=230g/' \
+#    "${SPARK_CONF_DIR}/spark-env.sh"
 
 # create a starter script for non-daemonized spark workers
-cat > /tmp/sparkworker.sh <<EOF
+cat > ${TMPDIR}/sparkworker.sh <<EOF
 #! /bin/bash
 ulimit -u 16384 -n 16384
 export SPARK_CONF_DIR=${SPARK_CONF_DIR}
@@ -568,8 +577,8 @@ logf="${SCRATCH}/logs/spark-worker-\$(hostname).out"
 exec spark-class org.apache.spark.deploy.worker.Worker "${master}" &> "\${logf}"
 EOF
 
-chmod +x /tmp/sparkworker.sh
-sbcast /tmp/sparkworker.sh "${SCRATCH}/sparkworker.sh" \
+chmod +x ${TMPDIR}/sparkworker.sh
+srun cp ${TMPDIR}/sparkworker.sh "${SCRATCH}/sparkworker.sh" \
     || fail "Could not broadcast worker start scrip to nodes"
 
 ###
@@ -580,7 +589,7 @@ sbcast /tmp/sparkworker.sh "${SCRATCH}/sparkworker.sh" \
 trap 'shutdown_cluster' SIGUSR1
 
 # start master
-start-master.sh \
+spark-server/sbin/start-master.sh \
     || fail "Master did not start"
 sleep 30
 
